/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DateField: typeof import('./components/DateField.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    FileInput: typeof import('./components/FileInput.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    ModalForm: typeof import('./components/ModalForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./components/SelectField.vue')['default']
    TextField: typeof import('./components/TextField.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    VButton: typeof import('./components/VButton.vue')['default']
    VLogo: typeof import('./components/VLogo.vue')['default']
    VToggle: typeof import('./components/VToggle.vue')['default']
  }
}
